In [2]:
import pandas as pd

In [5]:
a = pd.Series([1,2,3,4,5])

In [6]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
type(a)

pandas.Series

In [8]:
a[2]

np.int64(3)

In [9]:
a = pd.Series(['a', 'b', 'c'])

In [10]:
a

0    a
1    b
2    c
dtype: str

In [12]:
a = pd.date_range(start = '2026-01-05', end = '2026-01-30')

In [13]:
a

DatetimeIndex(['2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01-17', '2026-01-18', '2026-01-19', '2026-01-20',
               '2026-01-21', '2026-01-22', '2026-01-23', '2026-01-24',
               '2026-01-25', '2026-01-26', '2026-01-27', '2026-01-28',
               '2026-01-29', '2026-01-30'],
              dtype='datetime64[us]', freq='D')

In [14]:
type(a)

pandas.DatetimeIndex

Pandas dataframe

In [15]:
import numpy as np

In [18]:
temp = np.random.randint(low = 20, high = 100, size = [20, ])
name = np.random.choice(['Abhay', 'Teclov', 'Greeksub', 'Ankit'], 20)
random = np.random.choice([10,11,13,12,14],20)

In [19]:
a = list(zip(temp,name,random))

In [20]:
df = pd.DataFrame(data = a, columns =['temp', 'name', 'random'])

In [21]:
df

    temp      name  random
0     49     Ankit      11
1     57     Ankit      14
2     34     Abhay      10
3     93     Abhay      11
4     67  Greeksub      12
5     43     Abhay      11
6     30     Ankit      10
7     39    Teclov      11
8     72     Ankit      14
9     35     Abhay      13
10    98    Teclov      12
11    87  Greeksub      10
12    78     Ankit      11
13    57  Greeksub      14
14    23    Teclov      11
15    38     Ankit      14
16    84    Teclov      11
17    83     Ankit      11
18    90    Teclov      14
19    22    Teclov      14

In [22]:
type(df)

pandas.DataFrame

In [ ]:
temp = np.random.randint(low = 20, high = 100, size = [20, ])
name = np.random.choice(['Abhay', 'Teclov', 'Greeksub', 'Ankit'], 20)
random = np.random.choice([10,11,13,12,14],20)

In [23]:
df = pd.DataFrame({'temp':temp, 'name':name,'random':random})

In [25]:
df

    temp      name  random
0     49     Ankit      11
1     57     Ankit      14
2     34     Abhay      10
3     93     Abhay      11
4     67  Greeksub      12
5     43     Abhay      11
6     30     Ankit      10
7     39    Teclov      11
8     72     Ankit      14
9     35     Abhay      13
10    98    Teclov      12
11    87  Greeksub      10
12    78     Ankit      11
13    57  Greeksub      14
14    23    Teclov      11
15    38     Ankit      14
16    84    Teclov      11
17    83     Ankit      11
18    90    Teclov      14
19    22    Teclov      14

In [24]:
type(df)

pandas.DataFrame

In [26]:
df.head()

   temp      name  random
0    49     Ankit      11
1    57     Ankit      14
2    34     Abhay      10
3    93     Abhay      11
4    67  Greeksub      12

In [27]:
df.tail()

    temp    name  random
15    38   Ankit      14
16    84  Teclov      11
17    83   Ankit      11
18    90  Teclov      14
19    22  Teclov      14

In [28]:
df.shape

(20, 3)

In [29]:
df.columns

Index(['temp', 'name', 'random'], dtype='str')

In [30]:
df.name

0        Ankit
1        Ankit
2        Abhay
3        Abhay
4     Greeksub
5        Abhay
6        Ankit
7       Teclov
8        Ankit
9        Abhay
10      Teclov
11    Greeksub
12       Ankit
13    Greeksub
14      Teclov
15       Ankit
16      Teclov
17       Ankit
18      Teclov
19      Teclov
Name: name, dtype: str

In [31]:
df['temp']

0     49
1     57
2     34
3     93
4     67
5     43
6     30
7     39
8     72
9     35
10    98
11    87
12    78
13    57
14    23
15    38
16    84
17    83
18    90
19    22
Name: temp, dtype: int64

In [32]:
df['temp'].describe()

count    20.000000
mean     58.950000
std      25.265902
min      22.000000
25%      37.250000
50%      57.000000
75%      83.250000
max      98.000000
Name: temp, dtype: float64

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   temp    20 non-null     int64
 1   name    20 non-null     str
 2   random  20 non-null     int64
dtypes: int64(2), str(1)
memory usage: 612.0 bytes

In [34]:
df.values

array([[49, 'Ankit', 11],
       [57, 'Ankit', 14],
       [34, 'Abhay', 10],
       [93, 'Abhay', 11],
       [67, 'Greeksub', 12],
       [43, 'Abhay', 11],
       [30, 'Ankit', 10],
       [39, 'Teclov', 11],
       [72, 'Ankit', 14],
       [35, 'Abhay', 13],
       [98, 'Teclov', 12],
       [87, 'Greeksub', 10],
       [78, 'Ankit', 11],
       [57, 'Greeksub', 14],
       [23, 'Teclov', 11],
       [38, 'Ankit', 14],
       [84, 'Teclov', 11],
       [83, 'Ankit', 11],
       [90, 'Teclov', 14],
       [22, 'Teclov', 14]], dtype=object)

In [35]:
df.set_index('temp')

          name  random
temp
49       Ankit      11
57       Ankit      14
34       Abhay      10
93       Abhay      11
67    Greeksub      12
43       Abhay      11
30       Ankit      10
39      Teclov      11
72       Ankit      14
35       Abhay      13
98      Teclov      12
87    Greeksub      10
78       Ankit      11
57    Greeksub      14
23      Teclov      11
38       Ankit      14
84      Teclov      11
83       Ankit      11
90      Teclov      14
22      Teclov      14

In [36]:
df

    temp      name  random
0     49     Ankit      11
1     57     Ankit      14
2     34     Abhay      10
3     93     Abhay      11
4     67  Greeksub      12
5     43     Abhay      11
6     30     Ankit      10
7     39    Teclov      11
8     72     Ankit      14
9     35     Abhay      13
10    98    Teclov      12
11    87  Greeksub      10
12    78     Ankit      11
13    57  Greeksub      14
14    23    Teclov      11
15    38     Ankit      14
16    84    Teclov      11
17    83     Ankit      11
18    90    Teclov      14
19    22    Teclov      14

In [37]:
df.set_index('temp', inplace = True)

In [38]:
df

          name  random
temp
49       Ankit      11
57       Ankit      14
34       Abhay      10
93       Abhay      11
67    Greeksub      12
43       Abhay      11
30       Ankit      10
39      Teclov      11
72       Ankit      14
35       Abhay      13
98      Teclov      12
87    Greeksub      10
78       Ankit      11
57    Greeksub      14
23      Teclov      11
38       Ankit      14
84      Teclov      11
83       Ankit      11
90      Teclov      14
22      Teclov      14

In [39]:
df.sort_index(axis=0, ascending=False)

          name  random
temp
98      Teclov      12
93       Abhay      11
90      Teclov      14
87    Greeksub      10
84      Teclov      11
83       Ankit      11
78       Ankit      11
72       Ankit      14
67    Greeksub      12
57    Greeksub      14
57       Ankit      14
49       Ankit      11
43       Abhay      11
39      Teclov      11
38       Ankit      14
35       Abhay      13
34       Abhay      10
30       Ankit      10
23      Teclov      11
22      Teclov      14

In [40]:
df.sort_values(by='random', ascending=False)

          name  random
temp
57       Ankit      14
38       Ankit      14
90      Teclov      14
72       Ankit      14
22      Teclov      14
57    Greeksub      14
35       Abhay      13
67    Greeksub      12
98      Teclov      12
23      Teclov      11
49       Ankit      11
93       Abhay      11
83       Ankit      11
78       Ankit      11
39      Teclov      11
43       Abhay      11
84      Teclov      11
34       Abhay      10
87    Greeksub      10
30       Ankit      10

In [44]:
df.iloc[[0,1]]

       name  random
temp
49    Ankit      11
57    Ankit      14

In [42]:
df.iloc[1:3,1]

temp
57    14
34    10
Name: random, dtype: int64

In [48]:
df.loc[39,:]

name      Teclov
random        11
Name: 39, dtype: object

In [49]:
df.loc[[39,84,34]]

        name  random
temp
39    Teclov      11
84    Teclov      11
34     Abhay      10

In [50]:
df.loc[[39,84],'name':'random']

        name  random
temp
39    Teclov      11
84    Teclov      11

In [52]:
df.loc[df.random > 13]

          name  random
temp
57       Ankit      14
72       Ankit      14
57    Greeksub      14
38       Ankit      14
90      Teclov      14
22      Teclov      14

In [53]:
df.loc[(df.random >13) | (df.random == 13)]

          name  random
temp
57       Ankit      14
72       Ankit      14
35       Abhay      13
57    Greeksub      14
38       Ankit      14
90      Teclov      14
22      Teclov      14

In [57]:
#pip install openpyxl

In [59]:
#pip install xlrd

In [10]:
df1 = pd.read_csv('weather.csv')

In [61]:
df1

      location        date  precipitation  temp_max  temp_min  wind  weather
0      Seattle  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1      Seattle  2012-01-02           10.9      10.6       2.8   4.5     rain
2      Seattle  2012-01-03            0.8      11.7       7.2   2.3     rain
3      Seattle  2012-01-04           20.3      12.2       5.6   4.7     rain
4      Seattle  2012-01-05            1.3       8.9       2.8   6.1     rain
...        ...         ...            ...       ...       ...   ...      ...
2917  New York  2015-12-27            2.0      17.2       8.9   5.5     rain
2918  New York  2015-12-28            1.3       8.9       1.7   6.3     snow
2919  New York  2015-12-29           16.8       9.4       1.1   5.3     rain
2920  New York  2015-12-30            9.4      10.6       5.0   3.0     rain
2921  New York  2015-12-31            1.5      11.1       6.1   5.5     rain

[2922 rows x 7 columns]

In [62]:
df1.to_excel('df_xl.xlsx', sheet_name='weather_data')

In [63]:
df2 = pd.read_excel('df_xl.xlsx')

In [64]:
df2

,Unnamed: 0,location,date,precipitation,temp_max,temp_min,wind,weather
0,0,Seattle,2012-01-01,0.0,12.8,5.0,4.7,drizzle
1,1,Seattle,2012-01-02,10.9,10.6,2.8,4.5,rain
2,2,Seattle,2012-01-03,0.8,11.7,7.2,2.3,rain
3,3,Seattle,2012-01-04,20.3,12.2,5.6,4.7,rain
4,4,Seattle,2012-01-05,1.3,8.9,2.8,6.1,rain
...,...,...,...,...,...,...,...,...
2917,2917,New York,2015-12-27,2.0,17.2,8.9,5.5,rain
2918,2918,New York,2015-12-28,1.3,8.9,1.7,6.3,snow
2919,2919,New York,2015-12-29,16.8,9.4,1.1,5.3,rain
2920,2920,New York,2015-12-30,9.4,10.6,5.0,3.0,rain
2921,2921,New York,2015-12-31,1.5,11.1,6.1,5.5,rain

In [65]:
df2.to_csv('file_noindex.csv', index = False)

In [3]:
# Merging & Concat

d1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['col1', 'number'])
d2 = pd.DataFrame([['c', 3, 'lion'], ['d', 4, 'tiger']],columns=['letter', 'number', 'animal'])

In [4]:
d1

  col1  number
0    a       1
1    b       2

In [5]:
d2

  letter  number animal
0      c       3   lion
1      d       4  tiger

In [6]:
pd.concat([d1,d2],axis=0)

  col1  number letter animal
0    a       1    NaN    NaN
1    b       2    NaN    NaN
0  NaN       3      c   lion
1  NaN       4      d  tiger

In [7]:
pd.concat([d1,d2], axis=0, ignore_index=True)

  col1  number letter animal
0    a       1    NaN    NaN
1    b       2    NaN    NaN
2  NaN       3      c   lion
3  NaN       4      d  tiger

In [8]:
pd.concat([d1,d2], axis= 1)

  col1  number letter  number animal
0    a       1      c       3   lion
1    b       2      d       4  tiger

In [11]:
df1

      location        date  precipitation  temp_max  temp_min  wind  weather
0      Seattle  2012-01-01            0.0      12.8       5.0   4.7  drizzle
1      Seattle  2012-01-02           10.9      10.6       2.8   4.5     rain
2      Seattle  2012-01-03            0.8      11.7       7.2   2.3     rain
3      Seattle  2012-01-04           20.3      12.2       5.6   4.7     rain
4      Seattle  2012-01-05            1.3       8.9       2.8   6.1     rain
...        ...         ...            ...       ...       ...   ...      ...
2917  New York  2015-12-27            2.0      17.2       8.9   5.5     rain
2918  New York  2015-12-28            1.3       8.9       1.7   6.3     snow
2919  New York  2015-12-29           16.8       9.4       1.1   5.3     rain
2920  New York  2015-12-30            9.4      10.6       5.0   3.0     rain
2921  New York  2015-12-31            1.5      11.1       6.1   5.5     rain

[2922 rows x 7 columns]

In [12]:
df_group = df1.groupby("weather")

In [13]:
df_group

In [14]:
for wind in df_group:
    print(wind)

('drizzle',       location        date  precipitation  temp_max  temp_min  wind  weather
0      Seattle  2012-01-01            0.0      12.8       5.0   4.7  drizzle
26     Seattle  2012-01-27            0.0       6.7      -2.2   1.4  drizzle
45     Seattle  2012-02-15            0.0       7.2       0.6   1.8  drizzle
85     Seattle  2012-03-26            0.0      12.8       6.1   4.3  drizzle
103    Seattle  2012-04-13            0.0      15.0       3.9   4.0  drizzle
...        ...         ...            ...       ...       ...   ...      ...
2866  New York  2015-11-06            0.0      23.9      16.7   4.2  drizzle
2897  New York  2015-12-07            0.0      12.8       4.4   3.4  drizzle
2900  New York  2015-12-10            0.0      15.0       8.9   3.0  drizzle
2901  New York  2015-12-11            0.0      14.4       7.8   2.7  drizzle
2903  New York  2015-12-13            0.0      21.1      11.7   3.1  drizzle

[111 rows x 7 columns])
('fog',       location        date  precipitation  temp_max  temp_min  wind weather
192    Seattle  2012-07-11            0.0      27.8      13.3   2.9     fog
260    Seattle  2012-09-17            0.0      27.8      11.7   2.2     fog
266    Seattle  2012-09-23            0.0      19.4      10.0   1.4     fog
267    Seattle  2012-09-24            0.0      21.1      10.0   1.8     fog
330    Seattle  2012-11-26            0.0       9.4       1.7   3.8     fog
...        ...         ...            ...       ...       ...   ...     ...
2864  New York  2015-11-04            0.0      20.6      10.0   2.8     fog
2880  New York  2015-11-20            0.0      17.2       7.2   5.7     fog
2886  New York  2015-11-26            0.0      15.6       1.7   2.9     fog
2887  New York  2015-11-27            0.0      17.2       6.1   2.4     fog
2902  New York  2015-12-12            0.0      17.8       9.4   1.9     fog

[139 rows x 7 columns])
('rain',       location        date  precipitation  temp_max  temp_min  wind weather
1      Seattle  2012-01-02           10.9      10.6       2.8   4.5    rain
2      Seattle  2012-01-03            0.8      11.7       7.2   2.3    rain
3      Seattle  2012-01-04           20.3      12.2       5.6   4.7    rain
4      Seattle  2012-01-05            1.3       8.9       2.8   6.1    rain
5      Seattle  2012-01-06            2.5       4.4       2.2   2.2    rain
...        ...         ...            ...       ...       ...   ...     ...
2916  New York  2015-12-26            0.3      15.6       9.4   4.8    rain
2917  New York  2015-12-27            2.0      17.2       8.9   5.5    rain
2919  New York  2015-12-29           16.8       9.4       1.1   5.3    rain
2920  New York  2015-12-30            9.4      10.6       5.0   3.0    rain
2921  New York  2015-12-31            1.5      11.1       6.1   5.5    rain

[1087 rows x 7 columns])
('snow',       location        date  precipitation  temp_max  temp_min  wind weather
13     Seattle  2012-01-14            4.1       4.4       0.6   5.3    snow
14     Seattle  2012-01-15            5.3       1.1      -3.3   3.2    snow
15     Seattle  2012-01-16            2.5       1.7      -2.8   5.0    snow
16     Seattle  2012-01-17            8.1       3.3       0.0   5.6    snow
17     Seattle  2012-01-18           19.8       0.0      -2.8   5.0    snow
...        ...         ...            ...       ...       ...   ...     ...
2616  New York  2015-03-01           13.0       0.6      -6.6   2.1    snow
2618  New York  2015-03-03           17.8       2.2      -7.1   4.0    snow
2620  New York  2015-03-05           18.5       5.0      -6.0   5.9    snow
2635  New York  2015-03-20            8.4       4.4      -0.5   4.6    snow
2918  New York  2015-12-28            1.3       8.9       1.7   6.3    snow

[119 rows x 7 columns])
('sun',       location        date  precipitation  temp_max  temp_min  wind weather
7      Seattle  2012-01-08            0.0      10.0       2.8   2.0     sun
10     Seattle  2012-01-11            0.0       6.1      -1.1   5.1     sun
11     Seattle  2012-01-12            0.0       6.1      -1.7   1.9     sun
12     Seattle  2012-01-13            0.0       5.0      -2.8   1.3     sun
32     Seattle  2012-02-02            0.0       8.3       1.7   2.6     sun
...        ...         ...            ...       ...       ...   ...     ...
2898  New York  2015-12-08            0.0      10.6       4.4   3.5     sun
2899  New York  2015-12-09            0.0      12.8       1.1   3.4     sun
2909  New York  2015-12-19            0.0       5.0       2.2   9.0     sun
2910  New York  2015-12-20            0.0       6.7       1.7   5.1     sun
2911  New York  2015-12-21            0.0      12.8       3.3   5.3     sun

[1466 rows x 7 columns])

In [15]:
df_group.get_group('fog')

      location        date  precipitation  temp_max  temp_min  wind weather
192    Seattle  2012-07-11            0.0      27.8      13.3   2.9     fog
260    Seattle  2012-09-17            0.0      27.8      11.7   2.2     fog
266    Seattle  2012-09-23            0.0      19.4      10.0   1.4     fog
267    Seattle  2012-09-24            0.0      21.1      10.0   1.8     fog
330    Seattle  2012-11-26            0.0       9.4       1.7   3.8     fog
...        ...         ...            ...       ...       ...   ...     ...
2864  New York  2015-11-04            0.0      20.6      10.0   2.8     fog
2880  New York  2015-11-20            0.0      17.2       7.2   5.7     fog
2886  New York  2015-11-26            0.0      15.6       1.7   2.9     fog
2887  New York  2015-11-27            0.0      17.2       6.1   2.4     fog
2902  New York  2015-12-12            0.0      17.8       9.4   1.9     fog

[139 rows x 7 columns]

In [16]:
df_group.describe()

        precipitation                                                   \
                count      mean        std  min  25%  50%   75%    max
weather
drizzle         111.0  0.000000   0.000000  0.0  0.0  0.0  0.00    0.0
fog             139.0  0.000000   0.000000  0.0  0.0  0.0  0.00    0.0
rain           1087.0  7.212328  10.918681  0.0  0.8  3.0  9.40  118.9
snow            119.0  6.426891   7.910406  0.0  0.5  3.3  8.65   32.3
sun            1466.0  0.000000   0.000000  0.0  0.0  0.0  0.00    0.0

        temp_max             ... temp_min          wind                      \
           count       mean  ...      75%   max   count      mean       std
weather                      ...
drizzle    111.0  18.351351  ...    15.30  23.3   111.0  3.188288  1.298512
fog        139.0  17.923741  ...    13.30  23.9   139.0  2.994964  1.654083
rain      1087.0  15.708188  ...    12.80  25.0  1087.0  4.174057  1.818052
snow       119.0   3.713445  ...     0.60   5.6   119.0  5.895798  2.537595
sun       1466.0  18.386289  ...    14.85  26.7  1466.0  4.075375  1.803978


         min  25%  50%  75%   max
weather
drizzle  0.6  2.1  3.0  4.2   6.9
fog      0.8  1.8  2.6  3.8  10.1
rain     0.5  2.8  3.9  5.2  16.2
snow     1.6  4.1  5.4  7.9  12.9
sun      0.4  2.8  3.7  5.1  12.6

[5 rows x 32 columns]

In [18]:
def hot_temp(x):
    return x > 3

In [21]:
df1['hot_temp'] = df1['wind'].apply(hot_temp)

In [22]:
df1

,location,date,precipitation,temp_max,temp_min,wind,weather,hot_temp
0,Seattle,2012-01-01,0.0,12.8,5.0,4.7,drizzle,True
1,Seattle,2012-01-02,10.9,10.6,2.8,4.5,rain,True
2,Seattle,2012-01-03,0.8,11.7,7.2,2.3,rain,False
3,Seattle,2012-01-04,20.3,12.2,5.6,4.7,rain,True
4,Seattle,2012-01-05,1.3,8.9,2.8,6.1,rain,True
...,...,...,...,...,...,...,...,...
2917,New York,2015-12-27,2.0,17.2,8.9,5.5,rain,True
2918,New York,2015-12-28,1.3,8.9,1.7,6.3,snow,True
2919,New York,2015-12-29,16.8,9.4,1.1,5.3,rain,True
2920,New York,2015-12-30,9.4,10.6,5.0,3.0,rain,False
2921,New York,2015-12-31,1.5,11.1,6.1,5.5,rain,True

In [23]:
df1['hot_temp'] = df1['wind'].apply(lambda x: x > 4)

In [24]:
df1

,location,date,precipitation,temp_max,temp_min,wind,weather,hot_temp
0,Seattle,2012-01-01,0.0,12.8,5.0,4.7,drizzle,True
1,Seattle,2012-01-02,10.9,10.6,2.8,4.5,rain,True
2,Seattle,2012-01-03,0.8,11.7,7.2,2.3,rain,False
3,Seattle,2012-01-04,20.3,12.2,5.6,4.7,rain,True
4,Seattle,2012-01-05,1.3,8.9,2.8,6.1,rain,True
...,...,...,...,...,...,...,...,...
2917,New York,2015-12-27,2.0,17.2,8.9,5.5,rain,True
2918,New York,2015-12-28,1.3,8.9,1.7,6.3,snow,True
2919,New York,2015-12-29,16.8,9.4,1.1,5.3,rain,True
2920,New York,2015-12-30,9.4,10.6,5.0,3.0,rain,False
2921,New York,2015-12-31,1.5,11.1,6.1,5.5,rain,True

In [30]:
d1 = pd.DataFrame({
    "city" : ["lucknow", "Kanpur","agra","delhi"],
    "temperature" : [32,45,30,40]
})

In [34]:
d2 = pd.DataFrame({
    "city" : ["delhi", "lucknow", "Kanpur"],
    "humidity" : [68,65,75]
})

In [35]:
df = pd.merge(d1,d2, on='city')

In [36]:
df

      city  temperature  humidity
0  lucknow           32        65
1   Kanpur           45        75
2    delhi           40        68

In [37]:
pd.merge(d1,d2, on=['city'], how = 'outer')

      city  temperature  humidity
0   Kanpur           45      75.0
1     agra           30       NaN
2    delhi           40      68.0
3  lucknow           32      65.0

In [38]:
pd.merge(d1,d2, on=['city'], how='left')

      city  temperature  humidity
0  lucknow           32      65.0
1   Kanpur           45      75.0
2     agra           30       NaN
3    delhi           40      68.0

In [39]:
#pivot table

In [40]:
df1.pivot_table(values = 'wind', index = 'weather', aggfunc = 'mean')

             wind
weather
drizzle  3.188288
fog      2.994964
rain     4.174057
snow     5.895798
sun      4.075375