In [4]:
import pandas as pd

In [5]:
a = pd.Series([1,2,3,4,5])

In [6]:
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
type(a)

pandas.Series

In [8]:
a[2]

np.int64(3)

In [9]:
a = pd.Series(['a', 'b', 'c'])

In [10]:
a

0    a
1    b
2    c
dtype: str

In [12]:
a = pd.date_range(start = '2026-01-05', end = '2026-01-30')

In [13]:
a

DatetimeIndex(['2026-01-05', '2026-01-06', '2026-01-07', '2026-01-08',
               '2026-01-09', '2026-01-10', '2026-01-11', '2026-01-12',
               '2026-01-13', '2026-01-14', '2026-01-15', '2026-01-16',
               '2026-01-17', '2026-01-18', '2026-01-19', '2026-01-20',
               '2026-01-21', '2026-01-22', '2026-01-23', '2026-01-24',
               '2026-01-25', '2026-01-26', '2026-01-27', '2026-01-28',
               '2026-01-29', '2026-01-30'],
              dtype='datetime64[us]', freq='D')

In [14]:
type(a)

pandas.DatetimeIndex

Pandas dataframe

In [15]:
import numpy as np

In [18]:
temp = np.random.randint(low = 20, high = 100, size = [20, ])
name = np.random.choice(['Abhay', 'Teclov', 'Greeksub', 'Ankit'], 20)
random = np.random.choice([10,11,13,12,14],20)

In [19]:
a = list(zip(temp,name,random))

In [20]:
df = pd.DataFrame(data = a, columns =['temp', 'name', 'random'])

In [21]:
df

    temp      name  random
0     49     Ankit      11
1     57     Ankit      14
2     34     Abhay      10
3     93     Abhay      11
4     67  Greeksub      12
5     43     Abhay      11
6     30     Ankit      10
7     39    Teclov      11
8     72     Ankit      14
9     35     Abhay      13
10    98    Teclov      12
11    87  Greeksub      10
12    78     Ankit      11
13    57  Greeksub      14
14    23    Teclov      11
15    38     Ankit      14
16    84    Teclov      11
17    83     Ankit      11
18    90    Teclov      14
19    22    Teclov      14

In [22]:
type(df)

pandas.DataFrame

In [ ]:
temp = np.random.randint(low = 20, high = 100, size = [20, ])
name = np.random.choice(['Abhay', 'Teclov', 'Greeksub', 'Ankit'], 20)
random = np.random.choice([10,11,13,12,14],20)

In [23]:
df = pd.DataFrame({'temp':temp, 'name':name,'random':random})

In [25]:
df

    temp      name  random
0     49     Ankit      11
1     57     Ankit      14
2     34     Abhay      10
3     93     Abhay      11
4     67  Greeksub      12
5     43     Abhay      11
6     30     Ankit      10
7     39    Teclov      11
8     72     Ankit      14
9     35     Abhay      13
10    98    Teclov      12
11    87  Greeksub      10
12    78     Ankit      11
13    57  Greeksub      14
14    23    Teclov      11
15    38     Ankit      14
16    84    Teclov      11
17    83     Ankit      11
18    90    Teclov      14
19    22    Teclov      14

In [24]:
type(df)

pandas.DataFrame

In [26]:
df.head()

   temp      name  random
0    49     Ankit      11
1    57     Ankit      14
2    34     Abhay      10
3    93     Abhay      11
4    67  Greeksub      12

In [27]:
df.tail()

    temp    name  random
15    38   Ankit      14
16    84  Teclov      11
17    83   Ankit      11
18    90  Teclov      14
19    22  Teclov      14

In [28]:
df.shape

(20, 3)

In [29]:
df.columns

Index(['temp', 'name', 'random'], dtype='str')

In [30]:
df.name

0        Ankit
1        Ankit
2        Abhay
3        Abhay
4     Greeksub
5        Abhay
6        Ankit
7       Teclov
8        Ankit
9        Abhay
10      Teclov
11    Greeksub
12       Ankit
13    Greeksub
14      Teclov
15       Ankit
16      Teclov
17       Ankit
18      Teclov
19      Teclov
Name: name, dtype: str

In [31]:
df['temp']

0     49
1     57
2     34
3     93
4     67
5     43
6     30
7     39
8     72
9     35
10    98
11    87
12    78
13    57
14    23
15    38
16    84
17    83
18    90
19    22
Name: temp, dtype: int64

In [32]:
df['temp'].describe()

count    20.000000
mean     58.950000
std      25.265902
min      22.000000
25%      37.250000
50%      57.000000
75%      83.250000
max      98.000000
Name: temp, dtype: float64

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   temp    20 non-null     int64
 1   name    20 non-null     str
 2   random  20 non-null     int64
dtypes: int64(2), str(1)
memory usage: 612.0 bytes

In [34]:
df.values

array([[49, 'Ankit', 11],
       [57, 'Ankit', 14],
       [34, 'Abhay', 10],
       [93, 'Abhay', 11],
       [67, 'Greeksub', 12],
       [43, 'Abhay', 11],
       [30, 'Ankit', 10],
       [39, 'Teclov', 11],
       [72, 'Ankit', 14],
       [35, 'Abhay', 13],
       [98, 'Teclov', 12],
       [87, 'Greeksub', 10],
       [78, 'Ankit', 11],
       [57, 'Greeksub', 14],
       [23, 'Teclov', 11],
       [38, 'Ankit', 14],
       [84, 'Teclov', 11],
       [83, 'Ankit', 11],
       [90, 'Teclov', 14],
       [22, 'Teclov', 14]], dtype=object)

In [35]:
df.set_index('temp')

          name  random
temp
49       Ankit      11
57       Ankit      14
34       Abhay      10
93       Abhay      11
67    Greeksub      12
43       Abhay      11
30       Ankit      10
39      Teclov      11
72       Ankit      14
35       Abhay      13
98      Teclov      12
87    Greeksub      10
78       Ankit      11
57    Greeksub      14
23      Teclov      11
38       Ankit      14
84      Teclov      11
83       Ankit      11
90      Teclov      14
22      Teclov      14

In [36]:
df

    temp      name  random
0     49     Ankit      11
1     57     Ankit      14
2     34     Abhay      10
3     93     Abhay      11
4     67  Greeksub      12
5     43     Abhay      11
6     30     Ankit      10
7     39    Teclov      11
8     72     Ankit      14
9     35     Abhay      13
10    98    Teclov      12
11    87  Greeksub      10
12    78     Ankit      11
13    57  Greeksub      14
14    23    Teclov      11
15    38     Ankit      14
16    84    Teclov      11
17    83     Ankit      11
18    90    Teclov      14
19    22    Teclov      14

In [37]:
df.set_index('temp', inplace = True)

In [38]:
df

          name  random
temp
49       Ankit      11
57       Ankit      14
34       Abhay      10
93       Abhay      11
67    Greeksub      12
43       Abhay      11
30       Ankit      10
39      Teclov      11
72       Ankit      14
35       Abhay      13
98      Teclov      12
87    Greeksub      10
78       Ankit      11
57    Greeksub      14
23      Teclov      11
38       Ankit      14
84      Teclov      11
83       Ankit      11
90      Teclov      14
22      Teclov      14

In [39]:
df.sort_index(axis=0, ascending=False)

          name  random
temp
98      Teclov      12
93       Abhay      11
90      Teclov      14
87    Greeksub      10
84      Teclov      11
83       Ankit      11
78       Ankit      11
72       Ankit      14
67    Greeksub      12
57    Greeksub      14
57       Ankit      14
49       Ankit      11
43       Abhay      11
39      Teclov      11
38       Ankit      14
35       Abhay      13
34       Abhay      10
30       Ankit      10
23      Teclov      11
22      Teclov      14

In [40]:
df.sort_values(by='random', ascending=False)

          name  random
temp
57       Ankit      14
38       Ankit      14
90      Teclov      14
72       Ankit      14
22      Teclov      14
57    Greeksub      14
35       Abhay      13
67    Greeksub      12
98      Teclov      12
23      Teclov      11
49       Ankit      11
93       Abhay      11
83       Ankit      11
78       Ankit      11
39      Teclov      11
43       Abhay      11
84      Teclov      11
34       Abhay      10
87    Greeksub      10
30       Ankit      10

In [44]:
df.iloc[[0,1]]

       name  random
temp
49    Ankit      11
57    Ankit      14

In [42]:
df.iloc[1:3,1]

temp
57    14
34    10
Name: random, dtype: int64

In [48]:
df.loc[39,:]

name      Teclov
random        11
Name: 39, dtype: object

In [49]:
df.loc[[39,84,34]]

        name  random
temp
39    Teclov      11
84    Teclov      11
34     Abhay      10

In [50]:
df.loc[[39,84],'name':'random']

        name  random
temp
39    Teclov      11
84    Teclov      11

In [52]:
df.loc[df.random > 13]

          name  random
temp
57       Ankit      14
72       Ankit      14
57    Greeksub      14
38       Ankit      14
90      Teclov      14
22      Teclov      14

In [53]:
df.loc[(df.random >13) | (df.random == 13)]

          name  random
temp
57       Ankit      14
72       Ankit      14
35       Abhay      13
57    Greeksub      14
38       Ankit      14
90      Teclov      14
22      Teclov      14

In [57]:
#pip install openpyxl

In [59]:
#pip install xlrd